name: queens
channels:
  - conda-forge
# We want to have a reproducible setup, so we don't want default channels,
# which may be different for different users. All required channels should
# be listed explicitly here.
  - nodefaults
dependencies:
  - python==3.10
# to ensure that performance optimized backends are used,
# the following packages are installed from conda
# for example BLAS libraries like Intel MKL for numpy
  - cython==3.0.11
  - numba==0.60.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - libopenblas==0.3.28
# Only install pip-tools via pip itself since
# all other pip dependencies should be managed
# via pip-tools in the requirements.in files
  - pip
  - pip:
      - pip-tools
